"""case documents and llm usage kind

Revision ID: 0f2549585d12
Revises: 0f75e156ec4c
Create Date: 2026-10-02 12:05:48.376261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2549585d12'
down_revision: Union[str, Sequence[str], None] = '0f75e156ec4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_documents',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.add_column('llm_usage', sa.Column('kind', sa.String(length=16), server_default='explain', nullable=False))
    op.drop_constraint('llm_usage_pkey', 'llm_usage', type_='primary')
    op.create_primary_key('llm_usage_pkey', 'llm_usage', ['workspace_id', 'hour_start', 'kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM llm_usage WHERE kind <> 'explain'")
    op.drop_constraint('llm_usage_pkey', 'llm_usage', type_='primary')
    op.create_primary_key('llm_usage_pkey', 'llm_usage', ['workspace_id', 'hour_start'])
    op.drop_column('llm_usage', 'kind')
    op.drop_table('case_documents')
    # ### end Alembic commands ###
