"""letter generated body

Revision ID: 681b2a69995f
Revises: a2e396cb180c
Create Date: 2026-10-02 09:15:46.287324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "681b2a69995f"
down_revision: Union[str, Sequence[str], None] = "a2e396cb180c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("letters", sa.Column("generated_body", sa.Text(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("letters", "generated_body")
    # ### end Alembic commands ###
